### ISSUE TITLE
cannot build native library

### ISSUE THREAD

**Issue by viebel** [chrisseaton/graalvm-ten-things#3]
I'm following the steps in the README (7. Extend a native application).

I am running the community edition of GraalVM 
~~~bash
> java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183630.graal2.jdk8u-src-tar-gz-b03)
OpenJDK 64-Bit GraalVM CE 19.1.0 (build 25.212-b03-jvmci-20-b04, mixed mode)
~~~
I have been able to run with success the following command:
~~~bash
native-image --no-server -cp sis.jar:. --shared -H:Name=libdistance
~~~

However, when I run 
~~~bash
clang -I. -L. -ldistance distance.c -o distance
~~~
I get the following error:
~~~
distance.c:4:10: fatal error: 'libdistance.h' file not found
#include <libdistance.h>
         ^~~~~~~~~~~~~~~
1 error generated.
~~~

**Comment by chrisseaton** [comment]
Do you not have any headers generated from the `native-image` command? Has it produced any `.h` files in the current directory?

**Comment by viebel** [comment]
@chrisseaton It has produced two header files `graal_isolate.h` and `graal_isolate_dynamic.h`

**Comment by chrisseaton** [comment]
Ok I'll try reproducing - may take me a little while to get to it.

**Comment by viebel** [comment]
Ok. Thanks. If you can help me by the end of the week that'd be great!

**Comment by chrisseaton** [comment]
I can reproduce.

**Comment by chrisseaton** [comment]
Yes something is wrong here. Thanks for reporting. The only workaround I can suggest for now is to use 19.0.

**Comment by chrisseaton** [comment]
We found the bug and fixed it in https://github.com/oracle/graal/commit/f52c6ef6498b948816c828804013ae72d75bd883.

This won't be part of a release for a few weeks though.

Thanks for the report.
