### ISSUE TITLE
Is "javac" function not included in GraalVM(CE) by default???

### ISSUE THREAD

**Issue by Revolution2021** [chrisseaton/graalvm-ten-things#5]
Hi, 

This may be very simple question.
After installing GraalVM(CE) on my Linux(Ubuntu20), "javac" command does not work as below.

```
root@taro123:/opt/graalvm-ce-java11-21.3.0/graalvm-ten-things# javac TopTen.java
Command 'javac' not found, but can be installed with:
apt install default-jdk # version 2:1.11-72, or
apt install openjdk-11-jdk-headless # version 11.0.7+10-3ubuntu1
apt install ecj # version 3.16.0-1
apt install openjdk-8-jdk-headless # version 8u252-b09-1ubuntu1
root@taro123:/opt/graalvm-ce-java11-21.3.0/graalvm-ten-things# apt install default-jdk
```

After executing "apt install default-jdk" and installing "javac", it works as usual.

My simple question is;
Is GraalVM(CE) not enough or is the additional installation of "javac" required ?
(I thought that GraalVM includes "javac" function by default. Is my assumption wrong?)

Regards,

**Comment by chrisseaton** [comment]
GraalVM does include `javac`. Can you share how you were installing GraalVM or how you were setting your path?

**Comment by Revolution2021** [comment]
Thank you for your very quick clarification.

＞GraalVM does include javac.

I checked my PATH setting again and found that was problem.
Now. solved.

Thanks !!!
